apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 0
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            volumes:
              - name: cache-volume
                emptyDir:
                  medium: "Memory"
            containers:
                -   image: mysql:5.7
                    name: mysql
                    volumeMounts:
                      - mountPath: /var/lib/mysql
                        name: cache-volume
                    resources:
                        limits:
                            cpu: "1000m"
                            memory: "2Gi"
                    env:
                        -   name: MYSQL_ROOT_PASSWORD
                            value: app
                        -   name: MYSQL_USER
                            value: app
                        -   name: MYSQL_PASSWORD
                            value: app
                        -   name: MYSQL_DATABASE
                            value: shopware
---

apiVersion: v1
kind: Service
metadata:
    name: mysql
spec:
    type: ClusterIP
    ports:
        -   name: mysql
            port: 3306
    selector:
        app: mysql
