apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 0
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - image: shyim/shopware-platform-nginx:php74
                  name: nginx
                  resources:
                      limits:
                          memory: "2Gi"
                          cpu: "2000m"
---

apiVersion: v1
kind: Service
metadata:
    name: nginx
    annotations:
        dev.okteto.com/auto-ingress: "true"
spec:
    type: ClusterIP
    ports:
        - name: nginx
          port: 80
    selector:
        app: nginx
