name: shopware
image: shyim/shopware-cli:php74
command: ["bash"]
mountpath: "/var/www/html"
securityContext:
    runAsUser: 1000
    runAsGroup: 1000
forward:
    - 8080:8080
reverse:
    - 9000:9000
resources:
    limits:
        memory: "2Gi"
        cpu: "1000m"
services:
    - name: mysql
      image: mysql:5.7
    - name: nginx
      mountpath: "/var/www/html"
      environment:
          - HTTPS=on
